---
title: "Monocle bootstrap followup"
author: "Eric Kernfeld"
date: "November 2, 2016"
output: html_document
---

```{r}
# Relabels the branch with high Krt5 as "mTEC", high PRSS16 as "cTEC", zero as "branchpoint", and the other as "progenitor".
auto_relabel = function( cells, labels, K5, PRSS16, eday ){
  branch_means = aggregate.nice( data.frame(K5, PRSS16, eday), by = labels, FUN = mean )
  mTEC_label  = names( which.max( branch_means[, 1] ) )
  cTEC_label  = names( which.max( branch_means[, 2] ) )
  early_label = names( which.min( branch_means[, 3] ) )
  old_labels = sort( c( mTEC_label, cTEC_label, early_label, 0 ) )
  old_labels_should_be = sort( unique( labels ) )
  if( !all( old_labels == old_labels_should_be ) ){
    warning("Cannot auto-label this dataset. Returning original labels.")
  } else {
    labels[labels==0]  = "branchpoint"
    labels[labels==mTEC_label]  = "mTEC"
    labels[labels==cTEC_label]  = "cTEC"
    labels[labels==early_label] = "progenitor"
  }
  return( labels )
}
```

```{r}
results_path = Sys.getenv( "FREEZR_DESTINATION" )

# Branchmodel dependencies and usage
# devtools::install_github("ekernf01/branchmodel")
library( branchmodel )
library( ggplot2 )
library( assertthat )
library( princurve )
library( FNN )
library( kknn )
library( kernlab )
# data(demo_branch)
# head(demo_branch)
# dim(demo_branch)
# demo_mod = fit_branchmodel( demo_branch )
# plot_branchmodel( demo_mod )


# # Retrieve data and full Monocle run
dge_full  = inventory(tag = "monocle_sorted") %>% readRDS
mobj_full = inventory(tag = "monocle_sorted") %>% dirname %>% file.path( "mobj_TECs.data" ) %>% readRDS
bootstrap_results_path = inventory(tag="bootstrap_results") 

# # Retrieve and align bootstrap samples; put in giant dataframe
num_bootstrap_samples = 200
BRANCH_VIZ = c( "branch_viz_1", "branch_viz_2" )
VARS_FROM_BOOT = c( "barcode",	"eday",	"pseudotime",	"monocle_state", BRANCH_VIZ, "simple_branch" )
all_bootstrap = data.frame(matrix(nrow = 0, ncol = 8))
colnames( all_bootstrap ) = c( VARS_FROM_BOOT, "sample_idx" )
for( sample_idx in num_bootstrap_samples:1 ){
  f = paste0("monocle_results_", sample_idx, ".data")
  boot_out = read.table( file.path( bootstrap_results_path, f ), header = T, sep = "\t", stringsAsFactors = F )
  rownames(boot_out) = boot_out$barcode
  boot_out[, BRANCH_VIZ] = align_embedding_to_reference(  mat_samp =  as.matrix(boot_out[, BRANCH_VIZ]), 
                                                          mat_ref  =  t( mobj_full@reducedDimS[1:2, ] ) )
  boot_out$sample_idx = sample_idx 
  branch_mod = tryCatch( expr = {fit_branchmodel( boot_out[, BRANCH_VIZ] )}, 
                         error = function(e) return("branchmodel_fail") )
  if(identical("branchmodel_fail", branch_mod)){
    boot_out$simple_branch = NA
  } else {
    names( branch_mod@assignments ) = rownames( branch_mod@raw_data )
    ordered_labels = branch_mod@assignments[boot_out$barcode]
    boot_out$simple_branch = auto_relabel( cells = boot_out$barcode, 
                                           labels = ordered_labels,
                                           K5 = dge_full@data[ "Krt5", boot_out$barcode ], 
                                           PRSS16 = dge_full@data[ "Prss16", boot_out$barcode ],
                                           eday = dge_full@data.info[ boot_out$barcode, "eday" ] )
  }
  all_bootstrap = rbind( all_bootstrap, boot_out[, colnames( all_bootstrap ) ] )
  write.table( boot_out, file.path( results_path, f ), 
               quote = F, sep = "\t", row.names = F, col.names = T )
}
write.table( all_bootstrap, file.path( results_path, "bootstrap_samples.txt" ), 
             quote = F, sep = "\t", row.names = F, col.names = T )
rm(boot_out)  # don't want this cluttering things up outside the loop

# # Gather full-data run into df with same variables
original = dge_full %>% FetchData( c("eday",	"pseudotime",	"branch", BRANCH_VIZ) )
original$barcode = rownames(original)
original$sample_idx = "original"
original %<>% rename( c("branch"="monocle_state"))
branch_mod = fit_branchmodel( original[, BRANCH_VIZ] )
names( branch_mod@assignments ) = rownames( branch_mod@raw_data )
ordered_labels = branch_mod@assignments[original$barcode]
original$simple_branch = auto_relabel( cells = original$barcode, 
                                       labels = ordered_labels,
                                       K5 = dge_full@data[ "Krt5", original$barcode ], 
                                       PRSS16 = dge_full@data[ "Prss16", original$barcode ],
                                       eday = dge_full@data.info[ original$barcode, "eday" ] )
original = original[, colnames( all_bootstrap ) ]
atae(colnames( original ), colnames( all_bootstrap ) )
write.table( original, file.path( results_path, "full_run.txt" ), 
             quote = F, sep = "\t", row.names = F, col.names = T )
```
