---
title: "Monocle bootstrap followup"
author: "Eric Kernfeld"
date: "November 2, 2016"
output: html_document
---

####Data assembly

```{r}
results_path = Sys.getenv( "FREEZR_DESTINATION" )
BRANCH_VIZ = c( "branch_viz_1", "branch_viz_2" )
NUM_BOOT_AVAILABLE = 200

dge_full  = inventory( tag = "monocle_sorted") %>% readRDS
all_bootstrap = inventory( tag = "bootstrap_results_assembled" ) %>% 
  read.table( stringsAsFactors = F, header = T )
original      = inventory( tag = "bootstrap_results_assembled" ) %>% dirname %>% file.path( "full_run.txt" ) %>%
  read.table( stringsAsFactors = F, header = T )
rownames(original) = as.character(original$barcode)

# Add some measures of variability
original$location_variability = NA
for( my_barcode in original$barcode ){
  original[my_barcode, "location_variability"] =  
    subset( all_bootstrap, barcode==my_barcode, select = BRANCH_VIZ ) %>% apply(2, var) %>% sum
}

# This function alleviates overplotting by condensing some cells. It is meant to act on one bootstrap run's worth of data.
bin_cells = function( my_df, numeric_vars = c("pseudotime", "eday") ){
  hex_data = hexbin::hexbin( my_df[BRANCH_VIZ] )
  hex_data = data.frame( x = hex_data@xcm, 
                         y = hex_data@ycm, 
                         count = hex_data@count )
  names(hex_data)[1:2] = BRANCH_VIZ
  # Back-calculate bin for each cell
  nearest_bin = FNN::get.knnx( query = my_df[BRANCH_VIZ], 
                               data = hex_data[BRANCH_VIZ], 
                               k = 1, algorithm = "cover_tree" )$nn.index %>% c
  for( v in numeric_vars ){ hex_data[[v]] = NA }
  agg_pt_eday = aggregate.nice( my_df[numeric_vars], by = nearest_bin, FUN = mean ) 
  hex_data[levels(factor(nearest_bin)), numeric_vars] = agg_pt_eday
  hex_data[["sample_idx"]] = my_df[["sample_idx"]][1]
  return(hex_data)
}

# Apply it to all data
original_reduced = bin_cells(original, numeric_vars = c("pseudotime", "eday", "location_variability" ) )
all_bootstrap_reduced = c()
for(i in 1:NUM_BOOT_AVAILABLE){
  all_bootstrap_reduced = rbind( all_bootstrap_reduced, bin_cells(subset(all_bootstrap, sample_idx == i)) )
}
all_bootstrap_reduced$sample_idx %<>% factor
all_bootstrap$sample_idx %<>% factor
```

####Basic summaries to start with

```{r}

tsne_colored( dge_full, results_path = results_path, 
              colour = "eday", cols.use = Thanksgiving_colors,
              axes = BRANCH_VIZ, axes_description = "monocle", overplot_adjust = F )
save_feature_plots( dge_full, results_path = results_path, 
                    gene_list = c( "Ackr4", "Vgll2",
                                   "Cldn4", "Cldn6",
                                   "Krtdap", "Krt5", "Pvrl4",
                                   "Psmb11", "Ccl25", "Cxcl12", 
                                   "Hes6", "Hes1" ),
                    gene_list_name = "branchpoint_genes",
                    cols.use = blue_gray_red, use_rank = T,
                    axes = BRANCH_VIZ, axes_description = "monocle", overplot_adjust = F )

branch_colors = c(scales::hue_pal()(2), "purple", "gray")
names(branch_colors) = c("mTEC", "cTEC", "progenitor", "branchpoint" )
p = ggplot(original) + ggtitle("Automated branch assignments") + 
  geom_point( aes_string(x = BRANCH_VIZ[[1]], y = BRANCH_VIZ[[2]], colour = "simple_branch")) + 
  scale_color_manual(values = branch_colors)
ggsave( file.path( results_path, "branch_assignments.pdf"       ), p, 
        width = 8, height = 7)
ggsave( file.path( results_path, "branch_assignments.png"       ), p + theme(legend.position = "none"), 
        width = 8, height = 7)
ggsave( file.path( results_path, "branch_assignments_noleg.pdf" ), p + theme(legend.position = "none"), 
        width = 8, height = 7)
  
```

####Bootstrap plotting functions

```{r}
#' Plot a small group of cells over multiple bootstrap replicates
#'
boot_plot_cell_group = function( desired_cells = NULL, desired_monocle_state = NULL, 
                                 num_boot = NUM_BOOT_AVAILABLE, colour_by_boot = F ){
  atae(is.null(desired_cells) + is.null(desired_monocle_state), 1)
  num_boot = min(num_boot, NUM_BOOT_AVAILABLE)
  main = paste0(length(desired_cells), " cells over ", num_boot, " bootstrap samples")
  if( !is.null( desired_monocle_state ) ){ 
    desired_cells = subset( original, monocle_state==desired_monocle_state, select = "barcode", drop = T)
    main = paste0("Monocle state ", desired_monocle_state, " (", length(desired_cells), " cells) over ", num_boot, " bootstrap runs")
  }
  data1 = subset( all_bootstrap, barcode %in% desired_cells & sample_idx %in% 1:num_boot ) 
  data1$role = ifelse(colour_by_boot, list(as.numeric(data1$sample_idx)), "Specified cells (bootstrap)" )[[1]]
  data2 = subset( original, barcode %in% desired_cells )
  data2$role = "Specified cells (full data)"
  data3 = subset( original, !(barcode %in% desired_cells) )
  data3$role = "Rest of full data"
  data_all = rbind(data1, rbind(data2, data3)[colnames(data1)]) 
  p = ggplot( data_all ) +  ggtitle(main) 
  p = p + geom_point( aes( x = branch_viz_1, y = branch_viz_2, colour = role, alpha = role ) )
  colors = c("Specified cells (full data)" = "black",
             "Rest of full data"           = "grey")
  alphas = c("Specified cells (full data)" = 0.5,
             "Rest of full data"           = 0.1)
  if( colour_by_boot ){
    colors = c( scales::hue_pal()(num_boot), colors )
    alphas = c( rep(0.5, num_boot), alphas )
    names(colors)[1:num_boot] = 1:num_boot
    names(alphas)[1:num_boot] = 1:num_boot
  } else {
    colors = c( colors, "Specified cells (bootstrap)" = "pink" )
    alphas = c( alphas, "Specified cells (bootstrap)" = 0.1 )
  }
  p = p + scale_color_manual( values = colors ) 
  p = p + scale_alpha_manual( values = alphas )
  return(p)
}
save_bootplot = function( desired_monocle_state, results_path, ... ){
  ggsave( file.path(results_path, paste0( "bootplot_state_", desired_monocle_state, ".pdf" ) ),
          boot_plot_cell_group( desired_monocle_state = desired_monocle_state, ... ),
          width = 8, height = 7 )
}

```

####Bootstrap plots

```{r}

# # ===== Look at cell-by-cell variability =====

# By plotting cells
boot_plot_cell_group( desired_monocle_state = 19 )
dir.create.nice(file.path(results_path, "cell_persistence"))
dir.create.nice(file.path(results_path, "cell_persistence_10boot"))
for(i in 35:1) {save_bootplot( i, results_path = file.path(results_path, "cell_persistence") )}
for(i in 35:1) {
  save_bootplot( i, results_path = file.path(results_path, "cell_persistence_10boot"), 
                 colour_by_boot = T, num_boot = 10 )
}

# By using summary statistics
p_cell_placement_var = ggplot( original ) + 
  ggtitle("Cell placement variability") +
  geom_point( aes( x = branch_viz_1, y = branch_viz_2,
                   colour = log1p( location_variability ) )) + 
  scale_color_gradientn(colours = blue_purple_red)
stretch = 1 + 0.01*nchar("log1p( location_variability )")
ggsave( filename = file.path( results_path, "cell_placement_var.pdf" ), p_cell_placement_var,
        width = 8*stretch, height = 7 )

# Same plot but with reduced data
p_cell_placement_var_reduced = ggplot( original_reduced ) + 
  ggtitle("Cell placement variability") +
  geom_point( aes( x = branch_viz_1, y = branch_viz_2,
                   size = count, colour = log1p( location_variability ) )) + 
  scale_color_gradientn(colours = blue_purple_red)
stretch = 1 + 0.01*nchar("log1p( location_variability )")
ggsave( filename = file.path( results_path, "cell_placement_var_reduced.pdf" ), p_cell_placement_var_reduced,
        width = 8*stretch, height = 7 )

# # ===== Plot bootstrap samples superimposed =====
some_bootstrap = subset(  all_bootstrap , sample_idx %in% 1:10 ) 
some_bootstrap_reduced = subset(  all_bootstrap_reduced , sample_idx %in% 1:10 ) 
p_superimposed_demo = ggplot( data = some_bootstrap_reduced) + 
  ggtitle("A few superimposed bootstrap samples") +
  geom_point( aes( x = branch_viz_1, y = branch_viz_2, 
                   colour = sample_idx , size = count ), alpha = 0.5 ) +
  geom_point( aes( x = branch_viz_1, y = branch_viz_2, size = count ), colour = "black", data = original_reduced )
stretch = 1 + 0.01*nchar("sample_idx")
ggsave( filename = file.path( results_path, "a_few_boots.pdf" ), p_superimposed_demo,
        width = 8*stretch, height = 7 )

# line-plot version. Still not clean enough
p_superimposed_line = ggplot() + ggtitle("A few superimposed bootstrap samples") + 
  geom_point( aes( x = branch_viz_1, y = branch_viz_2, size = count ), 
              colour = "black", 
              data = original_reduced ) + 
  geom_line( aes( x = branch_viz_1, y = branch_viz_2, 
                  colour = sample_idx, group = interaction(monocle_state, sample_idx)  ), 
             alpha = 0.5,
             data = some_bootstrap[order(some_bootstrap$pseudotime), ] ) 
ggsave( filename = file.path( results_path, "a_few_boots_clean.pdf" ), p_superimposed_line,
        width = 8, height = 7 )


# # ===== Plot bootstrap samples faceted =====
p_faceted_eday = ggplot( data = all_bootstrap ) + 
  ggtitle("All bootstrap samples colored by embryonic day") + 
  geom_point( aes( x = branch_viz_1, y = branch_viz_2, colour = eday )  ) + 
  facet_wrap( ~sample_idx ) + scale_color_gradientn(colors = Thanksgiving_colors)
ggsave( filename = file.path( results_path, "boots_faceted_eday.pdf" ), p_faceted_eday,
        width = 8, height = 10 )

p_faceted_eday_reduced = ggplot( data = all_bootstrap_reduced ) + 
  ggtitle("All bootstrap samples colored by embryonic day") + 
  geom_point( aes( x = branch_viz_1, y = branch_viz_2, colour = eday, size = count )  ) + 
  facet_wrap( ~sample_idx ) + scale_color_gradientn(colors = Thanksgiving_colors)
ggsave( filename = file.path( results_path, "boots_faceted_eday_reduced.pdf" ), p_faceted_eday_reduced,
        width = 32, height = 40 )
ggsave( filename = file.path( results_path, "boots_faceted_eday_reduced.png" ), p_faceted_eday_reduced,
        width = 32, height = 40 )





```
