---
title: "Figure drafts for Jan 2017 submission"
author: "Eric Kernfeld"
date: "January 18, 2017"
output: html_document
---

####Data loading, preprocessing, and QC

```{r}
results_path = Sys.getenv( "FREEZR_DESTINATION" )

# # Retrieve whole TECs plus 16.5 sorted
dge = inventory( tag = "whole_plus_sorted_16_explore" ) %>% readRDS
dge %<>% add_maehrlab_metadata("eday")

# # Relabel cTECs and mTECs
custom_feature_plot(dge, "Krt5")
custom_feature_plot(dge, "ident")
cell_type = dge@ident %>% as.character %>% as.integer
cell_type[cell_type==4] = "mTEC"
cell_type[cell_type==6] = "mTEC"
cell_type[cell_type!="mTEC"] = "cTEC"
names(cell_type) = dge@cell.names
dge = AddMetaData( dge, cell_type, "cell_type" )
custom_feature_plot(dge, "cell_type")
saveRDS( dge, file.path( results_path, "dge_labeled.data" ) )
```

####Show extra info on SNN clustering

```{r}
# # Extract top 10 eigenvectors of the SNN matrix to help visualize SNN's behavior
dge = inventory( today_dest, tag = "whole_plus_sorted_16_labeled" ) %>% readRDS
cell_index = order( dge@ident, rnorm(length(dge@ident)) )
dge %<>% BuildSNN( plot.SNN = T )
snn_eigs = irlba::partial_eigen( dge@snn.dense, n = 10, symmetric = T ) 
desired_order = c(4, 8, 10, 7, 6, 1, 9, 2, 3, 5 )
snn_features = snn_eigs$vectors[cell_index, desired_order]
positivify = function(x) {
  mostly_negative = mean(x<0) > mean(x>0)
  if( mostly_negative ){
    return( -x )
  } else {
    return( x )
  }
}
snn_features = apply(snn_features, 2, positivify)
colnames( snn_features ) = desired_order

cluster_colors = scales::hue_pal()(7)[replace_with_int_rank(as.character( dge@ident[cell_index] ))]
{
  pdf( file.path( results_path, "snn_small_heatmap.pdf" ) )
  heatmap( t(snn_features) , 
           Rowv = NA, Colv = NA, labCol = "",
           scale = "column",
           ColSideColors = cluster_colors,
           col = blue_gray_red )
  X = apply(t(snn_features), 2, standardize) 
  gplots::heatmap.2( seq( min( X ), max( X ), length.out = 30 ) %>% matrix(ncol = 2), col = blue_gray_red )
  dev.off()
}


{
  pdf(file.path( results_path, "snn_eigenvalues.pdf" ))
  snn_eigs$values %>% div_by_sum %>% barplot(main = "Relative variance captured by SNN components")
  dev.off()
}

# # Dendrogram to visualize cluster relationships
{
  pdf(file.path( results_path, "dendrogram.pdf" ))
  dge = BuildClusterTree(dge, do.plot = T)
  dev.off()
}

# # Heatmap a few handpicked genes to ID the clusters
p_heat = make_heatmap_for_table( dge = dge,
                                 genes_in_order = c("Cldn4", "Cldn3", "Aire", "Fezf2", "Cd80", "Psmb11", "Prss16", "Cd83", "Ackr4"),
                                 desired_cluster_order =  c(6, 4, 0, 2, 3, 5, 7),
                                 aggregator = mean,
                                 norm_fun = standardize )
p_heat = p_heat + ggtitle("cTEC/mTEC markers, average expression")
ggsave( filename = file.path( results_path, "heatmap_cluster_mean.pdf"),
        plot = p_heat,
        width = 6, height = 8)

dge_train = SubsetData( dge, ident.use = 1:10 )
dge_test = SubsetData( dge, ident.use = 0 )
dge_test = knn_classifier( dge_train = dge_train, dge_test = dge_test, my_transform = "PCA_20" )
dge_test %>% custom_feature_plot("classifier_ident")
dge_test %>% FetchData("classifier_ident") %>% table %>% percentify
dge_train %>% FetchData("ident") %>% table %>% percentify
de_genes = FindMarkers( dge, ident.1 = 0, test.use = "roc" )
de_genes$cluster = 0
de_genes$gene = rownames(de_genes)
de_genes = de_genes[order(de_genes$myAUC, decreasing = T), ]
head(de_genes, 20)
write.table( de_genes, file.path( results_path, "cluster_0_markers.txt" ), sep = "\t", row.names = F, col.names = T, quote = F )

mTEC_cTEC_genes = FindMarkers( dge, ident.1 = c(4, 6), ident.2 = c(2, 3, 5, 7), test.use = "roc" )
mTEC_cTEC_genes$gene = rownames(mTEC_cTEC_genes)
dge@data.info$cell_type %<>% as.character
dge@data.info$cell_type[dge@ident=="0"] = "0"
mTEC_cTEC_genes$cluster_0_expr = rowMeans(dge@data[mTEC_cTEC_genes$gene, dge@data.info$cell_type == "0"] )
mTEC_cTEC_genes$mTEC_expr = rowMeans(dge@data[mTEC_cTEC_genes$gene, dge@data.info$cell_type == "mTEC"] )
mTEC_cTEC_genes$cTEC_expr = rowMeans(dge@data[mTEC_cTEC_genes$gene, dge@data.info$cell_type == "cTEC"] )
mTEC_soft_rel_err = abs(mTEC_cTEC_genes$cluster_0_expr - mTEC_cTEC_genes$mTEC_expr) / (mTEC_cTEC_genes$mTEC_expr + 1)
cTEC_soft_rel_err = abs(mTEC_cTEC_genes$cluster_0_expr - mTEC_cTEC_genes$cTEC_expr) / (mTEC_cTEC_genes$cTEC_expr + 1)
mTEC_cTEC_genes$cluster_0_cTECness = mTEC_soft_rel_err - cTEC_soft_rel_err 

mTEC_cTEC_genes = mTEC_cTEC_genes[order(mTEC_cTEC_genes$cluster_0_cTECness, decreasing = T), ]
p = make_heatmap_for_table( dge = dge, 
                            genes_in_order = mTEC_cTEC_genes$gene, 
                            desired_cluster_order = c("cTEC", "mTEC", "0"), 
                            ident.use = "cell_type", normalize = "row")
ggsave(file.path(results_path, "cTEC_mTEC_genes_cluster0.pdf"), width = 4, height = 10)

flip_table = function(x){ x[nrow(x):1, ]}
mTEC_cTEC_genes[c("gene", "mTEC_expr", "cTEC_expr", "cluster_0_expr")] %>% 
  subset(cTEC_expr > mTEC_expr) %>% head(20) %>%
  write.table( file.path( results_path, "cluster_0_cTEC_like.txt" ),
               sep = "\t", row.names = F, col.names = T, quote = F )
mTEC_cTEC_genes[c("gene", "mTEC_expr", "cTEC_expr", "cluster_0_expr")] %>% 
  subset(mTEC_expr > cTEC_expr) %>% tail(20) %>% flip_table %>%
  write.table( file.path( results_path, "cluster_0_mTEC_like.txt" ),
               sep = "\t", row.names = F, col.names = T, quote = F )
```

####QC: sorted versus whole-thymus data

```{r}
dge %<>% add_maehrlab_metadata("FACS_sorting")
cells_16_sorted = dge %>% 
  FetchData(c("eday", "FACS_sorting")) %>% 
  subset(eday==16.5 & FACS_sorting != "Live cells") %>% 
  rownames
cells_16_whole  = dge %>% 
  FetchData(c("eday", "FACS_sorting")) %>% 
  subset(eday==16.5 & FACS_sorting == "Live cells") %>%
  rownames
atae( intersect( cells_16_sorted, cells_16_whole), character(0))
all_genes = rownames(dge@data)
whole_tec_16_expr  = dge %>% FetchDataZeroPad( all_genes, cells.use = cells_16_whole  ) %>% colMeans
dge_sorted_16_expr = dge %>% FetchDataZeroPad( all_genes, cells.use = cells_16_sorted ) %>% colMeans
whole_tec_16_prop  = dge %>% FetchDataZeroPad( all_genes, cells.use = cells_16_whole  ) %>% apply( 2, prop_nz )
dge_sorted_16_prop = dge %>% FetchDataZeroPad( all_genes, cells.use = cells_16_sorted ) %>% apply( 2, prop_nz )
{
  pdf( file.path( results_path, "sorted_whole_corr.pdf" ) )
  plot( whole_tec_16_expr, 
        dge_sorted_16_expr , 
        main = paste0("Day 16.5 total expression, r = ",
                      cor( whole_tec_16_expr, dge_sorted_16_expr ) %>% round( 2 ) ) )
  plot( whole_tec_16_prop, 
        dge_sorted_16_prop, 
        main = paste0("Day 16.5 proportion expressing, r = ", 
                      cor( whole_tec_16_prop, dge_sorted_16_prop ) %>% round( 2 ) ) )
  dev.off()
}

```